name: undealer
description: 'A new Flutter project.'
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: ^3.10.7

dependencies:
    flutter:
        sdk: flutter
    vector_math: ^2.1.2
    cupertino_icons: ^1.0.8
    simple_gradient_text: ^1.4.0
    animate_gradient: ^0.0.4
    flutter_inset_shadow: ^2.0.3
    dotted_border: ^3.1.0
    provider: ^6.1.5+1
    flutter_floating_bottom_bar: ^1.3.0
    scaffold_gradient_background: ^1.0.3+1
    shared_preferences: ^2.2.2

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^6.0.0

flutter:
    uses-material-design: true
    fonts:
        - family: Lexend
          fonts:
              - asset: assets/fonts/Lexend-VariableFont_wght.ttf
